name: Spec Tests

on: [pull_request]

jobs:
  tests:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/chekcout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn add
        run: yarn test:ci
      - name: tests
        run: yarn test
